package com.example.helper.error

enum class ErrorCodes(val code: String) {

    ERROR_PARAM_FRONT("ERROR_PARAM_FRONT"),
    NOT_CONNECTION("NOT_CONNECTION"),
    TOTAL_FALL("TOTAL_FALL"),
    VALIDATE_ERROR("TL0010"),
    ERROR_CONSULTING_SERVICE_LIST_SIGN("SRL001"),
    NO_PENDING_OPERATIONS_LIST_SIGN("SRL002"),
    NOT_RESULT_FILTER_LIST_SIGN("SRL003"),
    NOT_APPLY_FILTER_LIST_SIGN("SRL004"),
    SELECT_MAX_OEPRATION_LIST_SIGN("SRL005"),
    NOT_PERMISSION_SIGN_LIST_SIGN("SRL006")

}
